version: 2
jobs:

  # Test all parts of the project are ok
  test:
    docker:

      - image: circleci/node:8

    steps:
      - checkout

      # Test portoflio-fabricator
      - run:
          name: install NPM dependencies
          command: |
            cd fabricated-website
            npm install

      - run:
          name: build
          command: |
            npm run build

      # Test portfolio-management/admin-ui
      - run:
          name: install NPM dependencies
          command: |
            cd ..
            cd portfolio-management/admin-ui
            npm install

      - run:
          name: build
          command: |
            npm run build

workflows:
  version: 2
  build_and_publish:
    jobs:
      - test
