# Deploy on push to master
#
#	1. build the project
#	2. deploy the project

# It relies on the `FIREBASE_TOKEN` secret being available in this repo.

name: deploy-portfolio-manager

on:
  push:
    branches:
    - master
    paths:
    - 'portfolio-manager/**'

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build project
      run: |
        cd portfolio-manager
        npm ci
        npm run build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: 'portfolio-manager'